# Generated by Django 3.1.7 on 2021-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlist',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentlist',
            name='lon',
            field=models.FloatField(),
        ),
    ]
