# Generated by Django 3.1.7 on 2021-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0002_auto_20210309_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.IntegerField()),
                ('photo_id', models.IntegerField()),
                ('server', models.IntegerField()),
                ('secret', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
