# Generated by Django 3.1.7 on 2021-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0005_auto_20210310_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
